### ISSUE TITLE
Release source code

### ISSUE THREAD

**Issue by rjurney** [LingxiaoShawn/GNNAsKernel#1]
This seems like the place to request the source code be posted :)

**Comment by tedtroxell** [comment]
Is there an expected timeline for the code release?

**Comment by GNNAsKernel** [comment]
We will release the code by the end of review discussion period of ICLR, which is Nov. 29. Thanks for waiting.

**Comment by GNNAsKernel** [comment]
Thank you for your patience. The code is published now!
