### ISSUE TITLE
One of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by steveazzolin** [LingxiaoShawn/GNNAsKernel#2]
Hi,

I encountered the following problem when running:  `python -m train.zinc model.mini_layers 0 model.gnn_type GCNConv`

```

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: 
[torch.cuda.FloatTensor [2941, 128]], which is output 0 of ReluBackward0, is at version 1; expected version 0 instead. 
Hint: enable anomaly detection to find the operation that failed to compute its gradient, with 
torch.autograd.set_detect_anomaly(True).

```

I am using Python 3.7.11 and torch 1.10.1.
Any ideas on how to solve this?

Thanks

**Comment by LingxiaoShawn** [comment]
I haven't met this problem with the same commend. Can you make sure that your environment setup is correct?

**Comment by Barcavin** [comment]
Hi,

The setup.sh seems not working anymore. Conda will encounter conflicts with the package specification in the setup.sh.
Is it possible to post the details of the environment where the code can run successfully?

Thanks

**Comment by LingxiaoShawn** [comment]
Hi please check again, I have updated to the newest package.

**Comment by Oceanusity** [comment]
Hello, I have the same problem, and I open a new issue to post the details. Thank you for your attention and help.
