### ISSUE TITLE
some question

### ISSUE THREAD

**Issue by YUZHIWANG-bug** [LingxiaoShawn/GNNAsKernel#4]
When I run the following file, it has the following error:
<img width="566" alt="image" src="https://user-images.githubusercontent.com/72587415/201903715-45886bb3-798c-475d-88ea-325ff6fbdb3d.png">
I'm surprised that this file exists in the project, but it reports an error. I'm a novice. Please teach me. Is my operation mode wrong?

**Comment by LingxiaoShawn** [comment]
have you used python -m?

**Comment by YUZHIWANG-bug** [comment]
> have you used python -m?
Thank you for your reply. Do you mean I should use it this way, like:python -m pyg_gnn_wrapper.py. Or use the case you provided, like: python -m train.zinc model.mini_layers 0 model.gnn_type GINEConv and so on.

**Comment by LingxiaoShawn** [comment]
you shouldn't access any model inside the core. You should treat core as a whole component and access it outside, like the way I demonstrated under train/ folder.

**Comment by YUZHIWANG-bug** [comment]
> you shouldn't access any model inside the core. You should treat core as a whole component and access it outside, like the way I demonstrated under train/ folder.
Thank you for your reply. I think I know，thank you very much！
