### ISSUE TITLE
 issues

### ISSUE THREAD

**Issue by zhouxuan1223** [LingxiaoShawn/GNNAsKernel#5]
Hello, when I run“python -m train.zinc model.mini_layers 0 model.gnn_type GINEConv”，There is one such error，Could you give me some insight on such a mistake？
![200276f1eb2484cfee5a81eea5d3dae](https://user-images.githubusercontent.com/118428322/203323589-0eac1424-256f-460d-ad28-b4eeed504eba.png)

**Comment by LingxiaoShawn** [comment]
I think you are not using the full version anaconda, and you are not using exact the setup I provided.

**Comment by zhouxuan1223** [comment]
I am very glad for your reply. I directly ran the setup you provided on the rented cloud server, and then installed the corresponding function package, but the above error occurred. I will try again. Once again, I would like to express my heartfelt thanks for your answer!
